apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ pvc_name }}"
  namespace: "{{ kubernetes_namespace }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ pvc_size }}"
