apiVersion: v1
kind: Service
metadata:
  name: "{{ service_name }}"
  namespace: "{{ kubernetes_namespace }}"
spec:
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
